INSERT INTO roles (name, permissions)
VALUES ('ROLE_USER', 'READ:USER'),
       ('ROLE_STAFF', 'READ:USER,CREATE:DOCUMENT,READ:DOCUMENT,UPDATE:DOCUMENT'),
       ('ROLE_MANAGER', 'READ:USER,UPDATE:USER,CREATE:DOCUMENT,READ:DOCUMENT,UPDATE:DOCUMENT,DELETE:DOCUMENT,APPROVED:DOCUMENT,DOWNLOAD:DOCUMENT'),
       ('ROLE_ADMIN', 'CREATE:USER,READ:USER,UPDATE:USER,CREATE:DOCUMENT,READ:DOCUMENT,UPDATE:DOCUMENT,DELETE:DOCUMENT,APPROVED:DOCUMENT,DOWNLOAD:DOCUMENT'),
       ('ROLE_SYSADMIN', 'CREATE:USER,READ:USER,UPDATE:USER,DELETE:USER,CREATE:DOCUMENT,READ:DOCUMENT,UPDATE:DOCUMENT,DELETE:DOCUMENT,APPROVED:DOCUMENT,DOWNLOAD:DOCUMENT');
